- README.md
LLVM provides prebuilt `lld` only for Apple Silicon, but not for x86_64. This leads to a download error when running the generator on Intel machines or under Rosetta. We should mark this CPU platform as WIP for macOS hosts until we can build `lld` as a generation step.
> Mark x86_64 macOS hosts WIP in `README.md`

- Sources/GeneratorCLI/GeneratorCLI.swift
`--host-cpu-architecture` and `--target-cpu-architecture` are quite verbose options, `--target-arch` and `--host-arch` seem to be nicer to use as shorthands.
> Make CPU architecture options shorter

- Package.resolved
- Package.swift
There have been no releases of AsyncAlgorithms for some time until now with `1.0.0-alpha`, which apparently provides a bugfix for `combineLatest` operator that we use. It doesn't look like `from: "1.0.0"` allows SwiftPM to pick up this prerelease version, so I've specified it as `exact`.
> Update to the latest tag of AsyncAlgorithms

- Sources/SwiftSDKGenerator/PathsConfiguration.swift
- Sources/SwiftSDKGenerator/Serialization/SwiftSDKMetadata.swift
- Utilities/soundness.sh
In accepted [SE-0387](https://github.com/apple/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md) "destinations" were renamed to "Swift SDKs". Based on that it feels more suitable to rename `Destination.swift` to `SwiftSDKMetadata.swift`. Also taking this as an opportunity to apply formatting cleanups and to update `Utilities/soundness.sh` to exclude the generated `./Bundles` directory from scanning.
> Fix formatting, rename `Destination.swift`

- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/Generator/LocalSwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
First step towards fixing https://github.com/apple/swift-sdk-generator/issues/9. To build `lld` on `x86_64` we need to download its sources first, and smallest source distributions are available at https://github.com/llvm/llvm-project/releases.
`DownloadableArtifacts` was also refactored to group hashes for different artifacts into fewer dictionaries.
> Allow downloading LLVM project source for building `lld`

- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
This brings `Triple.OS` closer to what's available in Swift Driver and SwiftPM.
> Add `case wasi` and `case win32` to the `Triple.OS` enum

- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/Generator/LocalSwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Build.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
Resolves https://github.com/apple/swift-sdk-generator/issues/9.
Resolves rdar://115890915.
> Build `lld` when no prebuilt binaries are available

- README.md
Marks x86_64 support as host platform, with a footnote clarifying additional build time and requirements.
Partially addresses https://github.com/apple/swift-sdk-generator/issues/20.
> Clarify x86_64 support in `README.md`

- Package.resolved
- Package.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
Latest release of AHC (0.19.0) deprecated `EventLoopGroupProvider.createNew`, we should be using `.singleton` instead.
> Fix `.createNew` deprecation in `EventLoopGroupProvider`

- Package.swift
- Sources/SwiftSDKGenerator/Generator/LocalSwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
- Sources/SwiftSDKGenerator/SystemUtils/Shell.swift
- Tests/SwiftSDKGeneratorTests/ArchitectureMappingTests.swift
We should enable complete concurrency checking by default, as it already uncovered an issue with `LocalSwiftSDKGenerator` sharing `self` with mutable properties (`var downloadArtifacts`) across different tasks.
The solution was to make `SwiftSDKGenerator` an actor to isolate direct access to that property and to prevent race conditions.
The only remaining few warnings on `throttle` will hopefully go away when https://forums.swift.org/t/pitch-region-based-isolation/67888/8 lands.
> Enable complete concurrency checking, fix warnings

- Package.swift
- Sources/SystemSQLite/module.modulemap
- Sources/SystemSQLite/sqlite.h
In subsequent PRs I'd like to introduce a SQLite-backed cache for storing hashes of generated artifacts. That will help us in avoiding redundant work and will make generator significantly quicker for re-runs that change only a few arguments.
> Add `SystemSQLite` target for future use in caching

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
This removes the need to run `docker rm` separately and reduces the risk of a dangling container being left behind if the cleanup process fails.
`docker run --rm` has the same behaviour as `docker rm -v` and will remove anonymous volumes associated with the container:
https://docs.docker.com/engine/reference/run/#clean-up---rm
> docker: docker run --rm removes container automatically on exit

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
Cross-compiling with Swift SDKs produced with Swift SDK Generator with `--static-swift-stdlib` passed to `swift build` in projects that use C interop (e.g. via `import Glibc`) leads to these errors:
```
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "SwiftGlibc.h"
```
The reason was that underlying Clang headers were present in `usr/lib/swift/clang` subdirectory of the `swift.xctoolchain` directory of the final bundle, but `usr/lib/swift_static/clang` was missing. These directories are identical, we should symlink one to the other for static linking to work.
Resolves rdar://115784447.
> Fix cross-compilation with static linking when using C interop

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
We've removed these subdirectories specified in `unusedDarwinPlatforms` constant previously from `usr/lib/swift`, but kept in `usr/lib/swift_static` by accident. Cleaning them up should reduce the size of the final Swift SDK bundle slightly.
> Remove unused Darwin platforms from the host toolchain

- Docker/Dockerfile
- Package.resolved
- Package.swift
- Sources/GeneratorEngine/Cache/CacheKeyProtocol.swift
- Sources/GeneratorEngine/Cache/FileCacheRecord.swift
- Sources/GeneratorEngine/Cache/SQLite.swift
- Sources/GeneratorEngine/Cache/SQLiteBackedCache.swift
- Sources/GeneratorEngine/Engine.swift
- Sources/GeneratorEngine/FileSystem/FileLock.swift
- Sources/GeneratorEngine/FileSystem/FileSystem.swift
- Sources/GeneratorEngine/FileSystem/LocalFileSystem.swift
- Sources/GeneratorEngine/FileSystem/OpenReadableFile.swift
- Sources/GeneratorEngine/FileSystem/OpenWritableFile.swift
- Sources/GeneratorEngine/FileSystem/ReadableFileStream.swift
- Sources/GeneratorEngine/FileSystem/VirtualFileSystem.swift
- Sources/GeneratorEngine/Query.swift
- Sources/Macros/CacheKeyMacro.swift
- Sources/Macros/Macros.swift
- Sources/Macros/QueryMacro.swift
- Sources/Macros/SimpleDiagnosticMessage.swift
- Sources/SystemSQLite/module.modulemap
- Sources/SystemSQLite/sqlite.h
- Tests/GeneratorEngineTests/EngineTests.swift
- Tests/MacrosTests/MacrosTests.swift
We'd like to avoid redundant rebuilding and regeneration for inputs that don't change. The new `GeneratorEngine` module achieves that by introducing a `Query` abstraction, which can be hashed and matched to its cached outputs if any are available.
The new `Engine` actor can run such `Query` and immediately return a cached result file if one is present and its hash matches the recorded one.
This required introducing new `@Query` and `@CacheKey` macros for making hashing easy and consistent on `QueryProtocol` types and their inputs.  We can't use the standard `Hashable` protocol, as that produces new hashes on every process launch due to randomized hashing seeds. With Swift Crypto's `HashFunction` we can generate consistent hashes and record them in `SQLiteBackedCache`.
To make the caching …
> Add `GeneratorEngine` module with tests and macros

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Without this, cross-compiling between a host and target with different CPU architectures when copying from Docker fails due to pulling the wrong Docker image.
> Specify platform when building Docker images

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
What looks like a search-replace error in 527128c7e21928d4e142f1165da5fa9c821cd076 added a spurious "await" in the target of the `rhel-ubi9.sdk/usr/lib64/libc.so` symlink:
x86_64-unknown-linux-gnu/rhel-ubi9.sdk/usr/lib64/libc.so -> libc.await so.6
This causes the linker to be unable to find libc:
% swift build --experimental-swift-sdk 5.9-RELEASE_rhel_ubi9_x86_64
Building for debugging...
warning: Could not read SDKSettings.json for SDK at: /Users/euanh/Library/org.swift.swiftpm/swift-sdks/5.9-RELEASE_rhel_ubi9_x86_64.artifactbundle/5.9-RELEASE_rhel_ubi9_x86_64/x86_64-unknown-linux-gnu/rhel-ubi9.sdk
<unknown>:0: warning: glibc not found for 'x86_64-unknown-linux-gnu'; C stdlib may be unavailable
<unknown>:0: warning: glibc not found for 'x86_64-unknown-linux-gnu'; C stdlib may be …
> Fix broken libc.so symlink in RHEL SDK built from Docker

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
We don't do anything in the `docker build` step and could just as easily run the upstream image directly.
Removing this step saves 6-10s on my machine.
> docker: Remove vestigial docker build

- README.md
- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Specifying the base container image gives the user a generic way
to build a custom SDK.   The base image might be:
* a nightly image published by the Swift project
* an image built by a private CI system
* a locally-built custom image including extra Linux libraries
This commit adds 2 new options:
--from-container-image: a reference to the custom container
image, overriding the templated default image name
--sdk-name: a custom name for the SDK bundle, overriding the
templated default SDK name
> docker: Support generating an SDK from a custom container image

- Package.resolved
- Package.swift
- Sources/SwiftSDKGenerator/Queries/DownloadArtifactQuery.swift
- Utilities/test.sh
The new release contained a breaking change renaming `throttle` to `_throttle`.
> Update `swift-async-algorithms` to 1.0.0-beta.1

- Sources/AsyncProcess/ProcessExecutor+Convenience.swift
- Sources/GeneratorEngine/FileSystem/FileLock.swift
- Sources/GeneratorEngine/FileSystem/FileSystem.swift
- Sources/GeneratorEngine/FileSystem/LocalFileSystem.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/Queries/DownloadFileQuery.swift
This makes it much easier to diagnose file system errors.
Also applied consistent formatting to some of the existing files.
Resolves https://github.com/apple/swift-sdk-generator/issues/48.
> Attach relevant `FilePath` values to `Errno` errors

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
f8a807edf044cab7fb244d531ad54d7159eeb874 moved the `lld` build into
CMakeBuildQuery.   This function is no longer used.
> generator: Remove unused buildCMakeProject function

- Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
When building from source, `ninja` builds all of LLVM, even though
we only need `lld`.   On my machine, asking it to build only
`bin/lld` shortens an SDK generator run with a cold cache by
about 6 minutes:
* `ninja` builds 2437 edges; overall SDK build is about 24 minutes. It produces about 90 files in bin, excluding symlinks.
* `ninja bin/lld` builds 1682 edges; overall SDK build is about 18 minutes. It produces 3 files in bin, excluding symlinks (lld, llvm-tblgen, llvm-lit).
> generator: When building from source, only build ldd

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
lld is always built as a full cross linker, able to handle all architectures and binary formats:
> It is always a cross-linker, meaning that it always supports all
> the above targets however it was built. In fact, we don’t provide
> a build-time option to enable/disable each target.
-- https://lld.llvm.org/#
It does not seem to be necessary to build _any_ LLVM targets.   With
LLVM_TARGETS_TO_BUILD set to the empty string, a viable lld binary
is still built.   On my machine this speeds up a cold-cache build by
another 4 minutes:
* Before: ninja builds 1682 edges; overall SDK build is about 18 minutes.
* After: ninja builds 1492 edges; overall SDK build is about 14 minutes.
> generator: Disable all libllvm targets when building lld

- Package.resolved
- Package.swift
- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/GeneratorEngine/Engine.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
- Sources/SwiftSDKGenerator/SystemUtils/Shell.swift
- Tests/SwiftSDKGeneratorTests/ArchitectureMappingTests.swift
This adds a dependency on the `ServiceLifecly` product from https://github.com/swift-server/swift-service-lifecycle.
Had to add a manual call to `withTaskCancellationHandler` in the current `Shell` implementation to propagate `SIGINT` to child processes on task cancellation.
I've also made `Engine` initializer and `shutDown` method internal, using `withEngine` pattern instead, which fixes shut down bugs that came up with task cancellation.
Also fixed `ArchitectureMappingTests.swift` not building due to recent changes and macOS CI being broken, while tests are temporarily disabled on Linux CI (tracked in https://github.com/apple/swift-sdk-generator/issues/45, reenabled in a subsequent PR).
Resolves rdar://116204896.
> Cancel tasks when receiving a `SIGINT` signal

- Sources/GeneratorCLI/GeneratorCLI.swift
These are the latest versions that we should use by default to get recent bug fixes included in produced Swift SDKs.
> Use Swift 5.9.1 and LLD 17.0.5 by default

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Since we currently don't support `--with-docker` for development snapshots, we shouldn't attempt to calculate `swiftBaseDockerImage` when `--with-docker` is not passed. Otherwise this triggers a `fatalError` crash.
> Fix `fatalError` failure for development snapshots

- Sources/GeneratorEngine/Engine.swift
`withEngine` currently swallows any error thrown from the closure - leading to errors being silently ignored and thus terminating the generator with a zero exit code but incomplete bundles.
> Rethrow error in `withEngine`

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
In addition to the one fixed in #55, I just found another one...
This one I've found by doing a quick search for `func with` and checking the results. So all these functions that start with `with` should be fine now.
Should have done that in #55 already...
> Rethrow error from `withHTTPClient`

- Package.swift
- Sources/GeneratorEngine/Engine.swift
- Sources/Helpers/ThrowingDefer.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Tests/HelpersTests/ThrowingDeferTests.swift
This offers a more generalized solution to the bugs fixed in #55 and #56 by adding a `Helpers` target that (currently) contains `withThrowingDefer` and `withAsyncThrowingDefer`.
Those functions basically do what was previously done manually at each such occasion:
- Run a given `work` closure
- Run a given `deferred` closure no matter what
- Re-throw errors from `work` or `deferred` (where errors from the latter take precedence).
Also, a new `withDockerContainer` function was added (fixes the swallowed error, which I also fixed in #58).
> Add (async) throwing defer helpers

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
The `withDockerContainer` wrapper calls `stopDockerContainer` after the wrapped closure returns.    `copyTargetSwiftFromDocker` was updated to use this wrapper, but it still calls `stopDockerContainer` itself. This means that when `withDockerContainer` tries to clean up, the container is already gone so the `stopDockerContainer` call fails:
docker stop 3c556c0bb3b401296312837ae15e3364f72b0f687cf516952ad80faa18071c69
3c556c0bb3b401296312837ae15e3364f72b0f687cf516952ad80faa18071c69
docker stop 3c556c0bb3b401296312837ae15e3364f72b0f687cf516952ad80faa18071c69
Error response from daemon: No such container: 3c556c0bb3b401296312837ae15e3364f72b0f687cf516952ad80faa18071c69
docker stop 3c556c0bb3b401296312837ae15e3364f72b0f687cf516952ad80faa18071c69
Error response from daemon: No such container: …
> generator: don't call `stopDockerContainer` directly

- Sources/GeneratorCLI/GeneratorCLI.swift
Update the default version Swift to pick up the latest bug fixes.
> generator: Use Swift 5.9.2 by default

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
In arm64 ubuntu images, some paths like e.g. `/usr/lib64` and `/usr/lib/arm64-linux-gnu` don't seem to exist.
I've added the possibility to ignore such failures, as well as a method to check for paths to exist in containers.
Let me know if there is a better way to check for paths in a container than how I did it.
Fixes apple/swift-sdk-generator#57.
~Also, I've found another case of a swallowed error here - which in case of #57 lead to follow-up errors later on.~
This is no longer a change in this PR - it was fixed by merging #59.
> Allow some paths to not exist when copying from containers

- README.md
- Sources/GeneratorCLI/GeneratorCLI.swift
This split out Linux-specific CLI options into `make-linux-sdk` subcommand, but keeps backwards compatibility by specifying it as the default subcommand.
```console
$ swift-sdk-generator make-linux-sdk --verbose --with-docker ...
$ swift-sdk-generator --verbose --with-docker ... # backward compatible
deprecated: Please explicity specify the subcommand to run. For example: $ swift-sdk-generator make-linux-sdk
```
There were two options in my mind to express recipe-specific options in CLI. The other one was something like below:
```
$ swift-sdk-generator --verbose --target-arch aarch64 -- --with-docker ...
```
But this style exceeds the swift-argument-parser's power and makes the help message slightly odd, so I chose the subcommand style.
>  Recipe: Add `make-linux-sdk` subcommand 

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/Helpers/Vendor/README.md
- Sources/Helpers/Vendor/Triple.swift
- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
- Sources/SwiftSDKGenerator/PlatformModels/VersionsConfiguration.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Sources/SwiftSDKGenerator/SystemUtils/UnixName.swift
- Tests/SwiftSDKGeneratorTests/ArchitectureMappingTests.swift
SwiftDriver's `Triple` parser is more robust than our bespoke one, and it's already tested.
* Replace all use of `Triple` with the SwiftDriver's one
* "uname -m" and "sw_vers" commands are replaced with libc `uname`
* Darwin version -> macOS version conversion is now done by the `Triple`
> Use SwiftDriver's `Triple` parser

- Sources/GeneratorCLI/GeneratorCLI.swift
This allows users to specify other triple fields like os and vendor. It's NFC at this moment but will be used to distinguish `wasm32-unknown-wasi` and `wasm32-unknown-none`
> Replace `--target-arch/--host-arch <arch>` with `--target/--host <triple>`

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Tests/SwiftSDKGeneratorTests/ArchitectureMappingTests.swift
Generalized `--{host,target}-swift-package-path` options to be common generator options based on @euanh's feedback https://github.com/apple/swift-sdk-generator/pull/74#discussion_r1464895574
> Add `--{host,target}-swift-package-path` to use self-built toolchains

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Currently, Wasm SDK contains whole host toolchain package contents, but some components are unnecessary and duplicated with the installed host toolchain.  This PR removes unused components as Linux SDK generator does, and in addition, removes lldb-related components.
The total reduction in `.artifactbundle` for Linux host is: 2.7GB -> 1.3GB ( -1.1GB by platform libraries and host tools, -300MB by lldb components)
I don't know if we should remove lldb components also in Linux SDK generator 🤔
> Remove unused toolchain components from WebAssembly SDK

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
Since #68, rebuilding a RHEL SDK bundle has failed with the following error unless the bundle is first deleted:
```
Error: The file “lib64” couldn’t be saved in the folder “rhel-ubi9.sdk” because a file with the same name already exists.
```
This is because the condition check around the cleanup logic was inverted when the check was moved into `LinuxRecipe.swift`.
https://github.com/apple/swift-sdk-generator/blob/5428358a282d53e4d714b90c0348a293cca0038d/Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator%2BEntrypoint.swift#L51-L52
https://github.com/apple/swift-sdk-generator/blob/b94744f2b3d89511145072d907a18c9ea6aa5578/Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift#L129-L130
This PR adds a test which tries to build an SDK twice without cleaning up in between.
> tests: Test that an SDK can be rebuilt without cleaning up

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Swift libraries for host platforms are linked by the Swift compiler tools, so they should not be removed from the toolchain directory.
I thought keeping `lib/host` is enough, but `swift-frontend` also links `../lib/linux/libswiftCore.so` on Linux host.
> Keep Swift libraries linked by compiler tools

- Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
PR#51 changed the recipe which builds `lld` from source so it would only build `lld` and not the rest of the `llvm` tools.  This change was lost in the transition to AsyncProcess in PR#77.
This change reduces a scratch build from about 19m30s to 16m on my machine (including time to fetch the archives).
> generator: Don't build other `llvm` binaries when building `lld` from source

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Host toolchain is not always needed for DEVELOPMENT snapshot now, so make it optional.
> WebAssembly: Make `--host-swift-package-path` optional for WebAssembly recipe

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
- Sources/SwiftSDKGenerator/Serialization/SwiftSDKMetadata.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
When compiler is vendored in the SDK, the resource directory is inferred from the location of the compiler executable. This is not the case when the compiler is not vendored, so we need to specify the resource directory explicitly to work with both cases.
> WebAssembly: Specify resource directory explicitly

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
The clang headers were copied from host toolchain at the first "rsync" step. But host toolchain can be optional, so we should copy the headers from the target toolchain instead.
> WebAssembly: Copy clang headers from target toolchain

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
`docker cp` tries to avoid creating simlinks which would break out of the directory it is creating.   In #88, when copying `/usr/lib/x86_64-linux-gnu` from a running container, a symlink pointing back 4 layers is rejected:
invalid symlink: <dest>/usr/lib/x86_64-linux-gnu/hdf5/serial/include" -> "../../../../include/hdf5/serial"
The intended target of the symlink is in `<dest>/usr/include` which is outside the path being copied.    The error message is generated here:
https://github.com/moby/moby/blob/dd146571ea458082c499c647ba36580bb7277131/pkg/archive/archive.go#L753
Symlinks which point inside the directory tree being copied do not cause errors:
<dest>/usr/lib/x86_64-linux-gnu/libxcb-render.so.0 -> libxcb-render.so.0.0.0
The "hdf5 include" error does not occur if we copy the whole of …
> generator: Handle symlinks when copying from a container

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/ArtifactsArchiveMetadata.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
- Tests/SwiftSDKGeneratorTests/ArchitectureMappingTests.swift
For SDKs that can be universally used on any host platform, the `supportedTriples` field in the SDK metadata was previously required to fill all possible host triples.
This change makes the `supportedTriples` field optional, allowing SDKs to be universally used without specifying any host triples, and Wasm SDK generator fills the field with null when `--host-swift-package-path` is not provided.
We need SwiftPM side support as well. https://github.com/apple/swift-package-manager/pull/7432
> Make `supportedTriples` optional in SDK metadata for universal SDKs

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
If `swift` is not installed in the final toolchain in the SDK, we don't need `swift-autolink-extract` either.
> Do not create a symlink for `swift-autolink-extract` if `swift` is not installed

- Sources/AsyncProcess/ChunkSequence.swift
- Sources/AsyncProcess/FileContentStream.swift
- Sources/AsyncProcess/ProcessExecutor+Convenience.swift
- Sources/AsyncProcess/ProcessExecutor.swift
- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/GeneratorEngine/Cache/SQLite.swift
- Sources/GeneratorEngine/FileSystem/FileSystem.swift
- Sources/GeneratorEngine/FileSystem/OpenReadableFile.swift
- Sources/GeneratorEngine/FileSystem/ReadableFileStream.swift
- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/PlatformModels/LinuxDistribution.swift
- Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
- Sources/SwiftSDKGenerator/PlatformModels/VersionsConfiguration.swift
- Sources/SwiftSDKGenerator/SystemUtils/GeneratorError.swift
Just removes `if` and `switch` *expressions*
> Make it Swift 5.8 compatible by trivial syntactic changes

- Package.swift
- Sources/AsyncProcess/NIOAsyncPipeWriter.swift
Reduce the number of dependencies to simplify the build process in apple/swift.
> Remove unused NIOExtras dependency

- Sources/GeneratorEngine/Cache/CacheKeyProtocol.swift
- Sources/GeneratorEngine/Query.swift
Follow-up to 3e076d11485793efc1fde511eb89d14a76d9b420
SystemString used inside FilePath is not a CacheKey, so the encoder complains about it, but we can consider FilePath as a leaf type and no need to encode it further.
> Fix `noCacheKeyConformance` error on `make-linux-sdk`

- Sources/GeneratorEngine/Engine.swift
- Sources/GeneratorEngine/Query.swift
- Tests/GeneratorEngineTests/EngineTests.swift
`CodingKeys` is automatically derived and defined as `private`, and types defined as private have anonymous context in its mangled name. Then `String(reflecting:)` returns the qualified name of the type including the anonymous context name, which contains the pointer address like `Item.(unknown context at $55eab1620198).CodingKeys` and the address can be different across runs due to ASLR.
So we need to stop encoding CodingKeys to reduce the possibility of undeterministic hash key. Our hashing strategy can be still underteministic if the cache key itself is declared as private, but we can't avoid it while keeping the cache key nominal type sensitive (not structurally sensitive).
> Fix undeterministic hash key due to pointer address in anonymous context name

- Package.resolved
- Package.swift
- Sources/GeneratorCLI/GeneratorCLI.swift
We have only single service in the project, so we don't need to orchestrate multiple services to gracefully shutdown. We can just run the single service and let it run until it finishes.
> Remove swift-service-lifecycle dependency

- Package.swift
- Sources/GeneratorEngine/Engine.swift
- Sources/GeneratorEngine/Query.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Queries/CMakeBuildQuery.swift
- Sources/SwiftSDKGenerator/Queries/DownloadArtifactQuery.swift
- Sources/SwiftSDKGenerator/Queries/DownloadFileQuery.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
- Sources/SwiftSDKGenerator/SystemUtils/ByteBuffer+Utils.swift
- Sources/SwiftSDKGenerator/SystemUtils/FileOperationError.swift
- Sources/SwiftSDKGenerator/SystemUtils/GeneratorError.swift
- Sources/SwiftSDKGenerator/SystemUtils/HTTPClient+Download.swift
- Tests/GeneratorEngineTests/EngineTests.swift
* Add a new abstraction `HTTPClientProtocol` to abstract the HTTP client operations.
* Add a new `OfflineHTTPClient` type that just throws an error when trying to download a file.
* Remove `httpClient` member from `Engine` and pass the HTTP client as a parameter to the queries that need it.
* Separate `Query` and `CacheKey` protocols to allow for queries having properties that are not part of the cache key.
> Make AsyncHTTPClient optional dependency

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
- Sources/SwiftSDKGenerator/PathsConfiguration.swift
- Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
Now SDK generator users are responsible for providing appropriate triples for their targets, so we don't need to convert them to the Linux convention anymore.
Also stop normalizing the triple string given through CLI options to keep the original triple string as is in the generated SDK metadata. This makes it more flexible to support various triple strings like wasm32-unknown-wasip1-threads.
> Remove `linuxConventionDescription` conversion

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Unpacking XZ-compressed archives (like `host_llvm_17.0.5_x86_64-unknown-linux.tar.xz`) with GNU tar requires either using the `-J` flag or none at all (rather than the `-z` flag, which seems to be reserved for gzip). On macOS, `-xzf` behaves like `-xf`, which is likely why this issue didn't come up there.
With `-xf` both macOS and GNU tar automatically recognize the right format.
> Untar using `-xf` instead of `-xzf`

- Utilities/test.sh
`-vv` makes logs too large and hard to read. We don't need that logging level right now and can easily bring it back when needed.
> Reduce Linux builds verbosity in `test.sh`

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
Resolves https://github.com/swiftlang/swift-sdk-generator/issues/121.
It doesn't seem that projects depending on Foundation can be cross-compiled with 6.0 Swift SDKs (`error: missing required module '_FoundationCShims'), but at least the generation process completes successfully.
> Fix a compatibility issue with Swift 6.0 and `main` snapshots

- Sources/GeneratorCLI/GeneratorCLI.swift
Verified manually that `swift-sdk-generator` itself can be cross-compiled when using https://github.com/swiftlang/swift-sdk-generator/pull/127.
> Bump default version of Swift to 5.10.1

- Sources/GeneratorCLI/GeneratorCLI.swift
> Fix `print` copy in `GeneratorCLI.swift`

- .gitignore
This allows SourceKit-LSP background indexing files to be ignored.
> Add `/.index-build` to `.gitignore`

- Sources/GeneratorCLI/GeneratorCLI.swift
Now that `Duration.formatted()` is available on non-Darwin platforms in Swift 6.0+ we can utilize it in `GeneratorCLI.swift` and address a long-standing `FIXME`.
> Address Foundation-related FIXME in `GeneratorCLI.swift`

- Sources/GeneratorEngine/Cache/CacheKey.swift
- Sources/GeneratorEngine/Query.swift
- Tests/GeneratorEngineTests/EngineTests.swift
Follow-up to https://github.com/swiftlang/swift-sdk-generator/pull/97 with an added test case that verifies direct `FilePath` encoding with `HashEncoder`.
> Check for `LeafCacheKey` in more `HashEncoder` functions

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Those files are recently added to the toolchain, and they are required to build Swift code that uses Foundation on WebAssembly.
We had been manually specifying the paths to copy from the target package into the SDK, but we now build host-agnostic SDKS. So we can just copy the whole `usr/lib` from the target Swift package into the SDK bundle instead of adding individual new paths. The host-specific build path is still used for 5.10 SDKs, so keep the old code as is for now, but it will be removed in the future.
> WasmSDK: Copy swift-foundation headers and apinotes into the Swift SDK bundle

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
Building with a Swift 6.0 SDK fails because the new `_FoundationCShims` framework headers can't be found:
<unknown>:0: error: missing required module '_FoundationCShims'
The necessary files are present in `$PLATFORM.sdk/usr/lib/swift`, but are not part of the list which is copied to
`$PLATFORM.sdk/usr/include`.  The Static Linux SDK and WASM SDK generator don't copy these files into /usr/include;  instead they set the `swiftResourcesPath` and `swiftStaticResourcesPath` fields in `swift-sdk.json`, which causes the build system to look in those paths for framework headers.
We can do the same for Linux SDKs, however we must stop copying the files to `/usr/include`, otherwise the build will fail because the framework header definitions are duplicated:
error: redefinition of module …
> generator/linux: Use `swiftResourcesPath` to find framework headers

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
Reverts swiftlang/swift-sdk-generator#139.  This change fixed Swift 6.0 container-based builds, but broke Debian-based builds.
See #141
> Revert "generator/linux: Use `swiftResourcesPath` to find framework headers"

- Docker/docker-compose.yaml
- Sources/SwiftSDKGenerator/SystemUtils/ByteBuffer+Utils.swift
- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
Building an SDK requires running the sdk-generator with `swift run swift-sdk-generator`.  This takes a lock on `.build`, but if the tests are being run by `swift test` the outer Swift Package Manager instance will already hold this lock, causing the test to deadlock. We can avoid this by giving the `swift run swift-sdk-generator` instance its own scratch directory.
This PR consolidates the code which builds SDKs in one function, then runs each SDK build with its own temporary scratch directory.   This avoids the deadlock on the `.build` directory when run under `swift test`.
The tests continue to pass when run under Xcode, which was not affected by the deadlock because it works in a separate scratch directory.
:warning: **The tests cannot currently run in CI because SDK generator cannot …
> tests: Fix EndToEnd test deadlock under `swift test`, but exclude from CI

- Sources/Helpers/Vendor/QueryEngine/CacheKey.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Queries/TarExtractQuery.swift
Extracting `lld` from the `llvm` archive takes about 40s on my machine, and
after the binary has been extracted a 5.5GB directory is left behind in the
`Artifacts` directory.
This change uses `tar` filters to reduce the number of files unpacked from
the archive and caches the resulting `lld` binary.
Excluding the time to download the archives, building an SDK from
Debian packages before `lld` has been cached takes about 57s on an
M3 MacBook Air.   A subsequent build with `lld` cached takes about
17s.
The SDKs generated by the old and new methods are identical.
This PR adds `CacheKey` conformance to `Array`, as suggested by 
@yingguqing in #106.   Adding this conformance to `Range` was not
necessary in this case.
> generator: Cache the lld binary after extracting it from the LLVM archive

- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
`swift run swift-sdk-generator` still builds a Linux SDK by default, but prints the following warning:
deprecated: Please explicitly specify the subcommand to run. For example: $ swift-sdk-generator make-linux-sdk
> tests: Silence warning about not using the make-linux-sdk subcommand

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
Issue https://github.com/swiftlang/swift-sdk-generator/issues/147 occurs because the ELF interpreter is found at different
paths, and with different names, on different architectures.    We
happen to pick up the x86_64 interpreter because it is stored in /lib64,
which we aready copy, but we miss the aarch64 interpreter.
An ELF binary contains an interpreter path which can point anywhere, but
there are defacto standard default locations.
* According to https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf)
the x86_64 / amd64 ABI specifies that the interpreter should be
at /lib/ld64.so.1, but Linux overrides this and uses
/lib64/ld-linux-x86-64.so.2.
* I couldn't find a similar document for ARM64 / aarch64 -
https://github.com/ARM-software/abi-aa/tree/main/aaelf64 is silent
on the …
> generator/linux: Copy ELF interpreter from architecture-specific locations

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
We still use 5.8 as a bootstrap compiler on CI, so we need to make sure that the code is compatible with it.
> Fix 5.8 compatibility

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
After Swift 6.0 the swift.org toolchain includes LLD, so it is not
necessary to install it separately from an LLVM archive.   The LLD
provided by the swift.org toolchain is also a multiarch binary, so
the SDK will run on both x86_64 and aarch64 macOS hosts.
This change slightly reduces the size of a Swift 6.0 SDK because 
currently these SDKs include two copies of LLD - one from the SDK
and one from LLVM.   This is because LLD is typically installed as
a single binary with multiple symlinks pointing to it representing
different 'personalities' such as `ld.lld`, `wasm-ld` and so on.   SDK
generator copies the `lld` binary in as `ld.lld`, overwriting one of
the symlinks:
-rwxr-xr-x   1 euanh  staff   108M 14 Nov  2023 ld.lld
lrwxr-xr-x   1 euanh  staff     3B 24 Oct 15:11 ld64.lld -> lld …
> generator/linux: Use the Swift 6.0 toolchain's lld

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
`copyTargetSwiftFromDocker()` already copies all the same files as `copyTargetSwift()`,
and puts them in the destination directory.   Calling `copyTargetSwift()` at the
end just results in several pointless rsync calls which sync the directories to
themselves.
Stopping in `copyTargetSwift()` shows that the source and destination arguments point to the same place:
Process 77272 stopped
* thread #2, queue = 'com.apple.root.default-qos.cooperative', stop reason = breakpoint 1.1 frame #0: ... at SwiftSDKGenerator+Copy.swift:105:8
102      }
103    }
104
-> 105    func copyTargetSwift(from distributionPath: FilePath, sdkDirPath: FilePath) async throws {
106      logGenerationStep("Copying Swift core libraries for the target triple into Swift SDK bundle...")
107
108      for (pathWithinPackage, …
> generator/linux: copyTargetSwiftFromDocker does not need to call copyTargetSwift

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
These changes reduce the size of the SDK by 450MB.   Not having
to extract and copy this data around slightly speeds up the process
of building an SDK.  On my machine
* Building a Swift 6.0 aarch64 SDK decreased from 23s to 22s
* Running the EndToEndTests decreased from 32m39s to 32m17s
The EndToEndTests continue to pass after this change.
> generator/linux: Exclude more unneeded platforms from the toolchain

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
This change makes it possible to compare generated SDKs using recursive diff, without having to account for spurious differences cause by the order of keys in JSON metadata files.
> generator: Sort keys in JSON metadata files

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
There are now many alternative container runtimes.   These often expose a socket interface which is compatible with the `docker` CLI, but may also have their own command line utilities.   For our limited requirements, these alternative CLIs are often compatible enough with the `docker` CLI that we can use them directly.
This PR adds an environment variable to allow users running alternative container runtimes to use their CLIs directly when building SDKs, removing the need to have the `docker` CLI tools installed as well.   I've tested the generator with `podman`; it produced identical SDKs to the current implementation (#171), with good performance.
The `docker` CLI is currently still required to run the SDK generator tests.
> generator: Add an environment variable to choose the container runtime

- Sources/GeneratorCLI/GeneratorCLI.swift
Not including the host toolchain matches the Swift Static Linux SDK.  Users with experience of the static SDK will be familiar with the need to install a matching OSS toolchain to use it:
https://www.swift.org/documentation/articles/static-linux-getting-started.html#installing-the-sdk
Not including the host toolchain reduces the size of the SDK
bundle by about 2GB.   This makes SDKs easier to move around,
wastes less storage space if multiple SDKs are installed, and
speeds up the SDK build process - especially the first build,
as the host toolchain does not have to be downloaded.
Wasm SDKs also do not include the host toolchain.
> generator: Do not include the host toolchain by default

- README.md
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
If --from-container-image is specified without --with-docker, the generator builds an SDK from Debian packages, completely ignoring the user's clear intent to build from a container image.
For now, we can assume that a user who specifies --from-container-image also wants to use a container runtime.  In future we might be able to support extracting container images without the need for a
runtime.   If that happens, we can stop assuming --with-docker
and commands which only specify --from-container-image will continue
to work, so scripts and documentation won't need to be changed.
> generator: --from-container-image implies --with-docker

- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
The end to end tests still assume that the host toolchain will be
embedded in the SDK.   There is currently no provision in the test
harness for installing a toolchain before running the tests, so for
now we must use the --host-toolchain flag when building SDKs.
> tests: End to end tests still require host toolchains

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
SDKs now do not include the host toolchain by default, but the generator still checks for host toolchains before deciding it does not need to download them.
Skipping this check when a host toolchain is not requested removes the
unnecessary  network request.    This saves a couple of seconds but also
makes it possible to run the generator offline, if building from a container
image which is already available locally.
> generator: Do not attempt to download toolchain if it is not needed

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
Some paths were being passed to container extraction commands (tar, docker cp) without quotes.  This caused the extraction to fail if the paths contained spaces.
> generator: Quote paths passed to container image extraction commands

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
All SDK generator log messages are now printed as structured logs
via a logger instance.   This includes the final message which tells
the user how to install and use the SDK.   All logger messages are
printed to standard error by default.
This PR changes the final installation message back to an ordinary
print, which will go to standard output.   This means that the user
will still see this message even if standard error is redirected.
It also fixes the end to end tests, which were failing because they
look for the bundle path from the generator's standard output.
> tests: Final SDK generator output should be printed to standard output

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/LinuxRecipeTests.swift
The [atomic library is used in the Swift stdlib](https://github.com/swiftlang/swift/blob/69756635819114a851023aa2e8e6fd87f51d094d/cmake/modules/AddSwift.cmake#L336-L338) for 32-bit architectures. As such, when attempting to compile a binary containing the static Swift stdlib using a Swift SDK for armv7, `-latomic` must be linked. This is not needed for regular cross-compilation, just when passing `--static-swift-stdlib`.
I've added `-latomic` for "armv7" and added a test case in `LinuxRecipeTests` to ensure that it is included in the toolset.json file.
Now, I can build my binary that contains the statically linked Swift stdlib with this command:
```
swift build --swift-sdk 6.0.3-RELEASE_debian_bookworm_armv7 --static-swift-stdlib
```
This generates a rather large binary when also linking …
> Fix support for building with `--static-swift-stdlib` for armv7

- .swift-format
- Sources/AsyncProcess/FileContentStream.swift
- Sources/AsyncProcess/ProcessExecutor+Convenience.swift
- Sources/AsyncProcess/ProcessExecutor.swift
- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Fixup.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Unpack.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator.swift
- Sources/SwiftSDKGenerator/PlatformModels/LinuxDistribution.swift
- Sources/SwiftSDKGenerator/Queries/DownloadArtifactQuery.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
- Sources/SwiftSDKGenerator/SystemUtils/ByteBuffer+Utils.swift
- Sources/SwiftSDKGenerator/SystemUtils/HTTPClient+Download.swift
- Sources/SwiftSDKGenerator/SystemUtils/which.swift
- Tests/AsyncProcessTests/AsyncByteBufferLineSequenceTests.swift
- Tests/AsyncProcessTests/IntegrationTests.swift
- Tests/GeneratorEngineTests/EngineTests.swift
- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
- Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/LinuxRecipeTests.swift
- Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/WebAssemblyRecipe.swift
Set `lineBreakBeforeEachArgument` to `true` for consistent formatting.
> Update `.swift-format` rules

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/PlatformModels/VersionsConfiguration.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
- Defaulted `swiftVersion` to "6.1-RELEASE".
- Added EndToEndTests for Ubuntu and RHEL for Swift61, including some additional tests for Ubuntu Jammy.
- Fixed missing /lib and /lib64 directories in Ubuntu Noble when building from deb packages. If these directories don't exist, they are symlinked to the correct directories in /usr, which is consistent to what happens when copying from the Docker containers.
- Added the fix for downloading Swift for the target that adds the platform name to the cache file, to avoid corruption of the artifacts: 
* <img width="375" alt="image" src="https://github.com/user-attachments/assets/b18efd38-2cbe-44e1-a6fd-2fbb1a13002b" />
ALSO: I did not include EndToEndTests for Fedora39 for Swift 6.1 since the container is non-existent, likely because it's EOL.
> Update defaults for Swift 6.1-RELEASE

- CONTRIBUTING.md
Utilities/soundness.sh was deleted in #199 which moved CI to GitHub Actions.
Credit to @heckj, who found the same problem in https://github.com/apple/swift-container-plugin/issues/96.
> docs: Delete instructions to run non-existent soundness.sh

- Package.swift
All of the CI jobs are using Swift 5.9 or later at this point.
> Bump `// swift-tools-version` to 5.9

- .swift-format
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
This seems to be a reasonable limit still readable on most devices, while reducing the amount of reformatting applied by `swift format` checks.
> Bump `lineLength` to 120 in `.swift-format`

- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
- Tests/SwiftSDKGeneratorTests/Generator/SwiftSDKGenerator+MetadataTests.swift
The generator incorrectly recorded absolute paths to Swift SDK metadata in bundle archive metadata, which is fragile and also can't be handled by SwiftPM.
> Fix use of absolute paths to Swift SDK metatadata

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
Embedded Swift looks up Clang's compiler-rt static library in a different path than non-embedded. These paths could be normalized in the future, but for now the easiest fix seems to be just to symlink the directory the static library is located in.
> Symlink `libclang_rt.builtins.a` for Embedded Swift for WASI

- .swift-format
- CONTRIBUTING.md
- Package.swift
- README.md
- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/Helpers/Vendor/QueryEngine/CacheKey.swift
- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Download.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Entrypoint.swift
- Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Metadata.swift
- Sources/SwiftSDKGenerator/PlatformModels/LinuxDistribution.swift
- Sources/SwiftSDKGenerator/PlatformModels/VersionsConfiguration.swift
- Sources/SwiftSDKGenerator/Serialization/SwiftSDKMetadata.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/SwiftSDKRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
- Sources/SwiftSDKGenerator/SystemUtils/ByteBuffer+Utils.swift
- Sources/SwiftSDKGenerator/SystemUtils/GeneratorError.swift
- Tests/SwiftSDKGeneratorTests/EndToEndTests.swift
- Tests/SwiftSDKGeneratorTests/Generator/SwiftSDKGenerator+MetadataTests.swift
- Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/LinuxRecipeTests.swift
- Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/WebAssemblyRecipe.swift
**Explanation**: This updates `release/6.2` branch of the generator used when building 6.2 Swift 6.2 toolchain with recent changes. Most notably:
* Embedded Swift SDK for WASI within existing Swift SDK for WASI artifact bundles, thanks to https://github.com/swiftlang/swift-package-manager/pull/8638
* Bump to Swift 5.9 in `// swift-tools-version`
* Bump to generating with Swift 6.1 release tag by default (as opposed to 6.0 previously)
* Support for Debian 11 and Debian 12 together with support for downloading and unpacking Debian packages as dependencies.
* Additional test suite additions that cover these changes.
**Scope**: Isolated to cross-compilation and only impacts existing Ubuntu toolchain job that generates Swift SDK for WASI.
**Risk**: Low, most of the changes LoC-wise were …
> Merge `main` into `release/6.2`

- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
- Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/WebAssemblyRecipe.swift
Embedded Swift Concurrency is currently broken, and linking this library leads to more issues. Let's exclude it for now.
> WebAssemblyRecipe: remove `-lswift_ConcurrencyDefaultExecutor` for embedded

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/Artifacts/DownloadableArtifacts.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/LinuxRecipe.swift
- Sources/SwiftSDKGenerator/SwiftSDKRecipes/WebAssemblyRecipe.swift
- Tests/SwiftSDKGeneratorTests/ArchitectureMappingTests.swift
- Tests/SwiftSDKGeneratorTests/SwiftSDKRecipes/LinuxRecipeTests.swift
This is necessary for correctness on macOS, where the concept of multi-arch binaries exists, and all swift.org toolchains for macOS are multi-arch.
> Add support for generating Swift SDKs with multiple host triples

- Sources/GeneratorCLI/GeneratorCLI.swift
- Sources/SwiftSDKGenerator/PlatformModels/Triple.swift
- Include FreeBSD version number in derived target triple
- Always use `rawValue` when using OS enum as string
CC @jakepetroules @MaxDesiatov
> FreeBSD improvements and bug fixes
